name: Tests
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install all dependecies
        run: npm i
      - name: Running all tests ....
        run: npm run test
